# Generated by Django 6.0.3 on 2026-05-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
