# Generated by Django 6.0.3 on 2026-05-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_fields', models.CharField(max_length=100, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, max_length=250, null=True, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'История изменения задачи',
                'verbose_name_plural': 'История изменения задач',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
