# Generated by Django 6.0.3 on 2026-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskhistory_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Стало'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Было'),
        ),
    ]
